---
engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      no-extend-native:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"